version: 0.2

phases:
  install:
    commands:
      - set -x
      - apt-get update && apt-get install -y curl
      - curl -sL https://deb.nodesource.com/setup_14.x | bash -
      - apt-get install -y nodejs
      - npm install -g yarn@1.22.19
      - yarn install
  build:
    commands:
      - yarn run android:build

artifacts:
  files:
    - 'android/app/build/outputs/apk/debug/app-debug.apk'
