version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14.x
    commands:
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
      - source ~/.bashrc
      - nvm install 14.0.0
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install -g yarn
  build:
    commands:
      - yarn install
      - yarn run android
