version: 0.2

phases:
  install:
      runtime-versions:
      nodejs: 14.x
    commands:
      - set -x
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
      - source ~/.bashrc
      - nvm install 14.0.0
      - npm install -g npm@latest
      - npm install -g yarn
      - yarn install
    
  build:
  builcommands:
      - yarn run android:build

artifacts:
  files:
    - 'android/app/build/outputs/apk/debug/app-debug.apk'
