version: 0.2

phases:
  build:
    commands:
      - set -x
      - npm install
      - npm -g install yarn
      - yarn install
      - npm -v
      - yarn -v
      - yarn run android

# Define a imagem para o ambiente de compilação
# Neste exemplo, estamos usando a imagem "aws standard x86_64-4.0"
# que suporta o Node.js 14
# Você pode escolher a imagem que melhor atende às suas necessidades
# Verifique a documentação da AWS para obter informações sobre as imagens de compilação
# suportadas e suas configurações
# https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html
image: aws/codebuild/standard:4.0
