version: 0.2

phases:
  install:
    commands:
      - set -x
      - npm install -g npm@latest
      - node -v
      - npm -v
      - yarn -v
      - yarn install
  build:
    commands:
      - yarn run android:build

artifacts:
  files:
    - 'android/app/build/outputs/apk/debug/app-debug.apk'
